# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

# Linter for CI of the PostgreSQL + Patroni docker image.
name: Lint (Hadolint)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
